# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ebd74e0a96ac65c6250613719600c47533838d5c749b3449e7b4968d9435418f577671a2b29ebe205a1abe551fc213e86c04ae57cd8267729a56c784204d68ef

test:
  secret_key_base: 8297c3c6924e288367b98dc635559a154f512079797dbf00d7cd67898437386cdecfe7eb3db7af3a8a986ce734f574eaeb4a1e09e58263e4d6f5b5023efe6b17

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
